--- 
document: 
  description: "La guida alle parole della Pubblica Amministrazione è glossario di termini ricorrenti che spesso generano dubbi di ortografia. Questa guida è parte delle risorse di Designers Italia dedicate alla progettazione di servizi pubblici digitali semplici, inclusivi e accessibili."
  name: "Guida alle parole della Pubblica Amministrazione"
  tags: 
    - linguaggio
    - design
